version: '3'

services:
        app:
            build:
                context: ./docker/app
                args:
                    - timezone=${TZ}
            volumes:
                - ./app:/srv:rw
                - ./app/var/log:/srv/var/log
            env_file:
                - .env
            environment:
                PHP_IDE_CONFIG: serverName=${NGINX_HOST}
            depends_on:
                - mysql
        nginx:
            build:
                context: ./docker/nginx
                args:
                    - nginx_host=${NGINX_HOST}
            ports:
                - "8080:80"
                - "443:443"
            depends_on:
                - app
            volumes:
                - ./app/public:/srv/public:ro
                - ./docker/nginx/default.template:/etc/nginx/conf.d/default.template
                - nginx_log:/var/log/nginx
            env_file:
                - .env
            command: /bin/bash -c "envsubst '$$NGINX_HOST'
                < /etc/nginx/conf.d/default.template
                > /etc/nginx/conf.d/default.conf
                && exec nginx -g 'daemon off;'"

        mysql:
            build:
                context: ./docker/db
                dockerfile: Dockerfile.mysql
            volumes:
                - ./.data/mysql:/var/lib/mysql:rw
            env_file:
                - .env
            ports:
                - "3307:3306"
volumes:
    app_log:
    nginx_log:
